// btdt/js/config-presets.js
window.BTDT_PRESETS = {
  studio: { title: 'Studio', color: 'corporate' },
  aurora: { title: 'Aurora', color: 'ocean' },
  paper: { title: 'Paper', color: 'white' },
  retro: { title: 'Retro', color: 'peach' },
  noir: { title: 'Noir', color: 'ink' },
  citrus: { title: 'Citrus', color: 'citrus' },
  calm: { title: 'Calm', color: 'arctic' },
  wild: { title: 'Wild', color: 'tropical' },
  sunset: { title: 'Sunset', color: 'sunset' },
  neon: { title: 'Neon', color: 'neon' },
  candy: { title: 'Candy', color: 'candy' },
  forest: { title: 'Forest', color: 'forest' },
  'nordic-elegance': { title: 'Nordic Elegance', color: 'nordic-frost' },
  'sakura-garden': { title: 'Sakura Garden', color: 'sakura' },
  'deep-space': { title: 'Deep Space', color: 'indigo-night' },
  'autumn-harvest': { title: 'Autumn Harvest', color: 'autumn' },
  'cyber-neon': { title: 'Cyber Neon', color: 'cyber-lime' },
  'vintage-journal': { title: 'Vintage Journal', color: 'vintage' },
  'emerald-palace': { title: 'Emerald Palace', color: 'emerald' },
  'berry-smoothie': { title: 'Berry Smoothie', color: 'berry' },
  'desert-mirage': { title: 'Desert Mirage', color: 'sandstone' },
  'clean-enterprise': { title: 'Clean Enterprise', color: 'clean-tech' },
  'royal-heritage': { title: 'Royal Heritage', color: 'royal' },
  'earth-explorer': { title: 'Earth Explorer', color: 'earth' },
  'techno-splash': { title: 'Techno Splash', color: 'vibrant-splash' },
  'serene-zen': { title: 'Serene Zen', color: 'serene' },
  'industrial-steel': { title: 'Industrial Steel', color: 'industrial' },
  'organic-life': { title: 'Organic Life', color: 'organic' },
  'power-grid': { title: 'Power Grid', color: 'power' },
  'lollipop-fun': { title: 'Lollipop Fun', color: 'lollipop' },
  'boutique-chic': { title: 'Boutique Chic', color: 'boutique' },
  'carbon-matrix': { title: 'Carbon Matrix', color: 'carbon' },
  'cobalt-pro': { title: 'Cobalt Pro', color: 'cobalt-power' },
  default: { title: 'Default', color: null }
};
